environment:
    url: "http://localhost"
sql:
    production:
        database: pop_db
    development:
        database: windowpane
        username: root
        password: root
        server: localhost:3306
    testing:
        database: pop_db_test